version: 3.9.{build}
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
after_build:
- ps: dotnet pack /p:Version=$env:APPVEYOR_BUILD_VERSION src\Elmah.Io.Client\Elmah.Io.Client.csproj --output artifacts
artifacts:
- path: '**\*.nupkg'