// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Elmah.Io.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CreateDeployment
    {
        /// <summary>
        /// Initializes a new instance of the CreateDeployment class.
        /// </summary>
        public CreateDeployment() { }

        /// <summary>
        /// Initializes a new instance of the CreateDeployment class.
        /// </summary>
        public CreateDeployment(string version = default(string), DateTime? created = default(DateTime?), string description = default(string), string userName = default(string), string userEmail = default(string))
        {
            Version = version;
            Created = created;
            Description = description;
            UserName = userName;
            UserEmail = userEmail;
        }

        /// <summary>
        /// The version number of this deployment. The value of version can be
        /// a SemVer compliant string or any other
        /// syntax that you are using as your version numbering
        /// scheme.
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

        /// <summary>
        /// When was this deployment created. Defaults to current time if not
        /// specified.
        /// </summary>
        [JsonProperty(PropertyName = "created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// Optional description of this deployment. Can be markdown or clear
        /// text.
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// The name of the person responsible for creating this deployment.
        /// This can be the name taken from
        /// your deployment server (like VSTS or Octopus).
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// The email of the person responsible for creating this deployment.
        /// This can be the email taken from
        /// your deployment server (like VSTS or Octopus).
        /// </summary>
        [JsonProperty(PropertyName = "userEmail")]
        public string UserEmail { get; set; }

    }
}
