// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Elmah.Io.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ElmahIoApiModelsMessagesResult
    {
        /// <summary>
        /// Initializes a new instance of the ElmahIoApiModelsMessagesResult
        /// class.
        /// </summary>
        public ElmahIoApiModelsMessagesResult() { }

        /// <summary>
        /// Initializes a new instance of the ElmahIoApiModelsMessagesResult
        /// class.
        /// </summary>
        public ElmahIoApiModelsMessagesResult(IList<ElmahIoApiModelsMessagesResultMessage> messages = default(IList<ElmahIoApiModelsMessagesResultMessage>), int? total = default(int?))
        {
            Messages = messages;
            Total = total;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "messages")]
        public IList<ElmahIoApiModelsMessagesResultMessage> Messages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

    }
}
