// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace Elmah.Io.Client
{
    /// <summary> Client options for ElmahIoAPIClient. </summary>
    public partial class ElmahIoAPIClientOptions : ClientOptions
    {
        private const ServiceVersion LatestVersion = ServiceVersion.Vv3;

        /// <summary> The version of the service to use. </summary>
        public enum ServiceVersion
        {
            /// <summary> Service version "v3". </summary>
            Vv3 = 1,
        }

        internal string Version { get; }

        /// <summary> Initializes new instance of ElmahIoAPIClientOptions. </summary>
        public ElmahIoAPIClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.Vv3 => "v3",
                _ => throw new NotSupportedException()
            };
        }
    }
}
