// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core.Pipeline;
using Elmah.Io.Client.Models;

namespace Elmah.Io.Client
{
    /// <summary> The Heartbeats service client. </summary>
    public partial class HeartbeatsClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        internal HeartbeatsRestClient RestClient { get; }

        /// <summary> Initializes a new instance of HeartbeatsClient for mocking. </summary>
        protected HeartbeatsClient()
        {
        }

        /// <summary> Initializes a new instance of HeartbeatsClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> server parameter. </param>
        internal HeartbeatsClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri endpoint = null)
        {
            RestClient = new HeartbeatsRestClient(clientDiagnostics, pipeline, endpoint);
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        /// <summary> Create a new heartbeat. </summary>
        /// <param name="id"> The ID of the heartbeat check. </param>
        /// <param name="logId"> The ID of the log containing the heartbeat check. </param>
        /// <param name="body"> The details of the heartbeat. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual async Task<Response> CreateAsync(string id, string logId, CreateHeartbeat body = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("HeartbeatsClient.Create");
            scope.Start();
            try
            {
                return await RestClient.CreateAsync(id, logId, body, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Create a new heartbeat. </summary>
        /// <param name="id"> The ID of the heartbeat check. </param>
        /// <param name="logId"> The ID of the log containing the heartbeat check. </param>
        /// <param name="body"> The details of the heartbeat. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        public virtual Response Create(string id, string logId, CreateHeartbeat body = null, CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("HeartbeatsClient.Create");
            scope.Start();
            try
            {
                return RestClient.Create(id, logId, body, cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }
    }
}
