// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Elmah.Io.Client.Models;

namespace Elmah.Io.Client
{
    internal partial class HeartbeatsRestClient
    {
        private Uri endpoint;
        private ClientDiagnostics _clientDiagnostics;
        private HttpPipeline _pipeline;

        /// <summary> Initializes a new instance of HeartbeatsRestClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> server parameter. </param>
        public HeartbeatsRestClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri endpoint = null)
        {
            endpoint ??= new Uri("");

            this.endpoint = endpoint;
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        internal HttpMessage CreateCreateRequest(string id, string logId, CreateHeartbeat body)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Post;
            var uri = new RawRequestUriBuilder();
            uri.Reset(endpoint);
            uri.AppendPath("/v3/heartbeats/", false);
            uri.AppendPath(logId, true);
            uri.AppendPath("/", false);
            uri.AppendPath(id, true);
            request.Uri = uri;
            if (body != null)
            {
                request.Headers.Add("Content-Type", "application/json-patch+json");
                var content = new Utf8JsonRequestContent();
                content.JsonWriter.WriteObjectValue(body);
                request.Content = content;
            }
            return message;
        }

        /// <summary> Create a new heartbeat. </summary>
        /// <param name="id"> The ID of the heartbeat check. </param>
        /// <param name="logId"> The ID of the log containing the heartbeat check. </param>
        /// <param name="body"> The details of the heartbeat. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/> or <paramref name="logId"/> is null. </exception>
        public async Task<Response> CreateAsync(string id, string logId, CreateHeartbeat body = null, CancellationToken cancellationToken = default)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (logId == null)
            {
                throw new ArgumentNullException(nameof(logId));
            }

            using var message = CreateCreateRequest(id, logId, body);
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);
            switch (message.Response.Status)
            {
                case 200:
                case 400:
                case 401:
                case 402:
                case 404:
                case 429:
                    return message.Response;
                default:
                    throw await _clientDiagnostics.CreateRequestFailedExceptionAsync(message.Response).ConfigureAwait(false);
            }
        }

        /// <summary> Create a new heartbeat. </summary>
        /// <param name="id"> The ID of the heartbeat check. </param>
        /// <param name="logId"> The ID of the log containing the heartbeat check. </param>
        /// <param name="body"> The details of the heartbeat. </param>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="id"/> or <paramref name="logId"/> is null. </exception>
        public Response Create(string id, string logId, CreateHeartbeat body = null, CancellationToken cancellationToken = default)
        {
            if (id == null)
            {
                throw new ArgumentNullException(nameof(id));
            }
            if (logId == null)
            {
                throw new ArgumentNullException(nameof(logId));
            }

            using var message = CreateCreateRequest(id, logId, body);
            _pipeline.Send(message, cancellationToken);
            switch (message.Response.Status)
            {
                case 200:
                case 400:
                case 401:
                case 402:
                case 404:
                case 429:
                    return message.Response;
                default:
                    throw _clientDiagnostics.CreateRequestFailedException(message.Response);
            }
        }
    }
}
