// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Elmah.Io.Client
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Heartbeats operations.
    /// </summary>
    public partial interface IHeartbeats
    {
        /// <summary>
        /// Create a new heartbeat.
        /// </summary>
        /// <param name='id'>
        /// The ID of the heartbeat check.
        /// </param>
        /// <param name='logId'>
        /// The ID of the log containing the heartbeat check.
        /// </param>
        /// <param name='heartbeat'>
        /// The details of the heartbeat.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse> CreateWithHttpMessagesAsync(string id, string logId, CreateHeartbeat heartbeat = default(CreateHeartbeat), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
