// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Elmah.Io.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A breadcrumb represent a step preceding a log message.
    /// </summary>
    public partial class Breadcrumb
    {
        /// <summary>
        /// Initializes a new instance of the Breadcrumb class.
        /// </summary>
        public Breadcrumb()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Breadcrumb class.
        /// </summary>
        /// <param name="dateTime">The date and time in UTC of the breadcrumb.
        /// If no date and time is provided, we will use the current date and
        /// time in UTC.</param>
        /// <param name="severity">An enum value representing the severity of
        /// this breadcrumb. The following values are allowed: Verbose, Debug,
        /// Information, Warning, Error, Fatal.</param>
        /// <param name="action">An action representing the breadcrumb. You can
        /// set a custom action or use one of the built-in: click, submit,
        /// navigation, request, error.</param>
        /// <param name="message">A message representing the breadcrumb. This
        /// should elaborate on the action.</param>
        public Breadcrumb(System.DateTime? dateTime = default(System.DateTime?), string severity = default(string), string action = default(string), string message = default(string))
        {
            DateTime = dateTime;
            Severity = severity;
            Action = action;
            Message = message;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the date and time in UTC of the breadcrumb. If no date
        /// and time is provided, we will use the current date and time in UTC.
        /// </summary>
        [JsonProperty(PropertyName = "dateTime")]
        public System.DateTime? DateTime { get; set; }

        /// <summary>
        /// Gets or sets an enum value representing the severity of this
        /// breadcrumb. The following values are allowed: Verbose, Debug,
        /// Information, Warning, Error, Fatal.
        /// </summary>
        [JsonProperty(PropertyName = "severity")]
        public string Severity { get; set; }

        /// <summary>
        /// Gets or sets an action representing the breadcrumb. You can set a
        /// custom action or use one of the built-in: click, submit,
        /// navigation, request, error.
        /// </summary>
        [JsonProperty(PropertyName = "action")]
        public string Action { get; set; }

        /// <summary>
        /// Gets or sets a message representing the breadcrumb. This should
        /// elaborate on the action.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
