// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Elmah.Io.Client.Models
{
    /// <summary> The CreateDeploymentResult. </summary>
    public partial class CreateDeploymentResult
    {
        /// <summary> Initializes a new instance of CreateDeploymentResult. </summary>
        internal CreateDeploymentResult()
        {
        }

        /// <summary> Initializes a new instance of CreateDeploymentResult. </summary>
        /// <param name="location"> The location of the created deployment. </param>
        internal CreateDeploymentResult(string location)
        {
            Location = location;
        }

        /// <summary> The location of the created deployment. </summary>
        public string Location { get; }
    }
}
