// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Elmah.Io.Client.Models
{
    /// <summary> The CreateHeartbeat. </summary>
    public partial class CreateHeartbeat
    {
        /// <summary> Initializes a new instance of CreateHeartbeat. </summary>
        public CreateHeartbeat()
        {
        }

        /// <summary> The result of this heartbeat. Can be &quot;Healthy, &quot;Degraded&quot;, or &quot;Unhealthy&quot;. Defaults to &quot;Healthy&quot;. </summary>
        public string Result { get; set; }
        /// <summary> If result is &quot;Degraded&quot; or &quot;Unhealthy&quot; you can use this property to specify why. </summary>
        public string Reason { get; set; }
        /// <summary>
        /// Optional string to identify which application logged this message. You can use this if you have multiple applications and services logging to the same log.
        /// 
        /// If not set, the application name &quot;Heartbeats&quot; will be set on all log messages generated from this heartbeat.
        /// </summary>
        public string Application { get; set; }
        /// <summary>
        /// Optional string to identify which version of your application logged this message. If not specified, any errors, warnings, or information messages will get
        /// 
        /// the newest version number created through deployment tracking as with normal log messages.
        /// </summary>
        public string Version { get; set; }
        /// <summary>
        /// Optional long for specifying how many milliseconds it took to execute the task resulting in this heartbeat. This can be used to get a better overview
        /// 
        /// of how long a scheduled task or service is running or to figure out if the grace period should be increased.
        /// </summary>
        public long? Took { get; set; }
    }
}
