// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Elmah.Io.Client.Models
{
    public partial class CreateHeartbeat : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Result))
            {
                writer.WritePropertyName("result");
                writer.WriteStringValue(Result);
            }
            if (Optional.IsDefined(Reason))
            {
                writer.WritePropertyName("reason");
                writer.WriteStringValue(Reason);
            }
            if (Optional.IsDefined(Application))
            {
                writer.WritePropertyName("application");
                writer.WriteStringValue(Application);
            }
            if (Optional.IsDefined(Version))
            {
                writer.WritePropertyName("version");
                writer.WriteStringValue(Version);
            }
            if (Optional.IsDefined(Took))
            {
                writer.WritePropertyName("took");
                writer.WriteNumberValue(Took.Value);
            }
            writer.WriteEndObject();
        }
    }
}
