// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Elmah.Io.Client.Models
{
    /// <summary> The CreateLogResult. </summary>
    public partial class CreateLogResult
    {
        /// <summary> Initializes a new instance of CreateLogResult. </summary>
        internal CreateLogResult()
        {
        }

        /// <summary> Initializes a new instance of CreateLogResult. </summary>
        /// <param name="location"> The location of the created log. </param>
        internal CreateLogResult(string location)
        {
            Location = location;
        }

        /// <summary> The location of the created log. </summary>
        public string Location { get; }
    }
}
