// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Elmah.Io.Client.Models
{
    /// <summary> The CreateMessageResult. </summary>
    public partial class CreateMessageResult
    {
        /// <summary> Initializes a new instance of CreateMessageResult. </summary>
        internal CreateMessageResult()
        {
        }

        /// <summary> Initializes a new instance of CreateMessageResult. </summary>
        /// <param name="location"> The location of the created message. </param>
        internal CreateMessageResult(string location)
        {
            Location = location;
        }

        /// <summary> The location of the created message. </summary>
        public string Location { get; }
    }
}
