// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Elmah.Io.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateHeartbeat
    {
        /// <summary>
        /// Initializes a new instance of the CreateHeartbeat class.
        /// </summary>
        public CreateHeartbeat()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateHeartbeat class.
        /// </summary>
        /// <param name="result">The result of this heartbeat. Can be "Healthy,
        /// "Degraded", or "Unhealthy". Defaults to "Healthy"</param>
        /// <param name="reason">If result is "Degraded" or "Unhealthy" you can
        /// use this property to specify why.</param>
        public CreateHeartbeat(string result = default(string), string reason = default(string))
        {
            Result = result;
            Reason = reason;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the result of this heartbeat. Can be "Healthy,
        /// "Degraded", or "Unhealthy". Defaults to "Healthy"
        /// </summary>
        [JsonProperty(PropertyName = "result")]
        public string Result { get; set; }

        /// <summary>
        /// Gets or sets if result is "Degraded" or "Unhealthy" you can use
        /// this property to specify why.
        /// </summary>
        [JsonProperty(PropertyName = "reason")]
        public string Reason { get; set; }

    }
}
