// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Elmah.Io.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateLogResult
    {
        /// <summary>
        /// Initializes a new instance of the CreateLogResult class.
        /// </summary>
        public CreateLogResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateLogResult class.
        /// </summary>
        /// <param name="location">The location of the created log.</param>
        public CreateLogResult(string location = default(string))
        {
            Location = location;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the location of the created log.
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

    }
}
