// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Elmah.Io.Client.Models
{
    /// <summary> The CreateLog. </summary>
    public partial class CreateLog
    {
        /// <summary> Initializes a new instance of CreateLog. </summary>
        /// <param name="name"> Name of the new log. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="name"/> is null. </exception>
        public CreateLog(string name)
        {
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }

            Name = name;
        }

        /// <summary> Name of the new log. </summary>
        public string Name { get; }
    }
}
