// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Elmah.Io.Client.Models
{
    /// <summary> The CreateDeployment. </summary>
    public partial class CreateDeployment
    {
        /// <summary> Initializes a new instance of CreateDeployment. </summary>
        /// <param name="version">
        /// The version number of this deployment. The value of version can be a SemVer compliant string or any other
        /// 
        /// syntax that you are using as your version numbering scheme.
        /// </param>
        /// <exception cref="ArgumentNullException"> <paramref name="version"/> is null. </exception>
        public CreateDeployment(string version)
        {
            if (version == null)
            {
                throw new ArgumentNullException(nameof(version));
            }

            Version = version;
        }

        /// <summary>
        /// The version number of this deployment. The value of version can be a SemVer compliant string or any other
        /// 
        /// syntax that you are using as your version numbering scheme.
        /// </summary>
        public string Version { get; }
        /// <summary> When was this deployment created in UTC. Defaults to current time if not specified. </summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary> Optional description of this deployment. Can be markdown or clear text. </summary>
        public string Description { get; set; }
        /// <summary>
        /// The name of the person responsible for creating this deployment. This can be the name taken from
        /// 
        /// your deployment server (like VSTS or Octopus).
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// The email of the person responsible for creating this deployment. This can be the email taken from
        /// 
        /// your deployment server (like VSTS or Octopus).
        /// </summary>
        public string UserEmail { get; set; }
        /// <summary>
        /// As default, deployments are attached all logs of the organization. If you want a deployment to
        /// 
        /// attach to a single log only, set this to the ID of that log.
        /// </summary>
        public string LogId { get; set; }
    }
}
