// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Elmah.Io.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateLog
    {
        /// <summary>
        /// Initializes a new instance of the CreateLog class.
        /// </summary>
        public CreateLog()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateLog class.
        /// </summary>
        /// <param name="name">Name of the new log.</param>
        public CreateLog(string name = default(string))
        {
            Name = name;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets name of the new log.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
