// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Elmah.Io.Client.Models
{
    public partial class CreateBulkMessageResult
    {
        internal static CreateBulkMessageResult DeserializeCreateBulkMessageResult(JsonElement element)
        {
            Optional<int> statusCode = default;
            Optional<string> location = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("statusCode"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    statusCode = property.Value.GetInt32();
                    continue;
                }
                if (property.NameEquals("location"))
                {
                    location = property.Value.GetString();
                    continue;
                }
            }
            return new CreateBulkMessageResult(Optional.ToNullable(statusCode), location.Value);
        }
    }
}
