// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Elmah.Io.Client.Models
{
    /// <summary> Represents a key value pair. </summary>
    public partial class Item
    {
        /// <summary> Initializes a new instance of Item. </summary>
        public Item()
        {
        }

        /// <summary> Initializes a new instance of Item. </summary>
        /// <param name="key"> The key of the item. </param>
        /// <param name="value"> The value of the item. </param>
        internal Item(string key, string value)
        {
            Key = key;
            Value = value;
        }

        /// <summary> The key of the item. </summary>
        public string Key { get; set; }
        /// <summary> The value of the item. </summary>
        public string Value { get; set; }
    }
}
