// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Elmah.Io.Client.Models
{
    public partial class Log
    {
        internal static Log DeserializeLog(JsonElement element)
        {
            Optional<string> id = default;
            Optional<string> name = default;
            Optional<string> color = default;
            Optional<string> environmentName = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"))
                {
                    id = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("color"))
                {
                    color = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("environmentName"))
                {
                    environmentName = property.Value.GetString();
                    continue;
                }
            }
            return new Log(id.Value, name.Value, color.Value, environmentName.Value);
        }
    }
}
