// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Elmah.Io.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Log
    {
        /// <summary>
        /// Initializes a new instance of the Log class.
        /// </summary>
        public Log()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Log class.
        /// </summary>
        /// <param name="id">ID of the log.</param>
        /// <param name="name">Name of the log.</param>
        /// <param name="color">Color of the log. The color will always be one
        /// of the following (green being the default):
        /// green, lightgreen, lime, yellow, orange, deeporange, red, pink,
        /// purple, deeppurple, blue, lightblue</param>
        /// <param name="environmentName">Environment name this log is in or
        /// "Other" if not in an environment.
        /// "Other" is chosen over null to mimic the experience in the elmah.io
        /// UI.</param>
        public Log(string id = default(string), string name = default(string), string color = default(string), string environmentName = default(string))
        {
            Id = id;
            Name = name;
            Color = color;
            EnvironmentName = environmentName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets ID of the log.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets name of the log.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets color of the log. The color will always be one of the
        /// following (green being the default):
        /// green, lightgreen, lime, yellow, orange, deeporange, red, pink,
        /// purple, deeppurple, blue, lightblue
        /// </summary>
        [JsonProperty(PropertyName = "color")]
        public string Color { get; set; }

        /// <summary>
        /// Gets or sets environment name this log is in or "Other" if not in
        /// an environment.
        /// "Other" is chosen over null to mimic the experience in the elmah.io
        /// UI.
        /// </summary>
        [JsonProperty(PropertyName = "environmentName")]
        public string EnvironmentName { get; set; }

    }
}
