// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Elmah.Io.Client.Models
{
    /// <summary> The MessagesResult. </summary>
    public partial class MessagesResult
    {
        /// <summary> Initializes a new instance of MessagesResult. </summary>
        internal MessagesResult()
        {
            Messages = new ChangeTrackingList<MessageOverview>();
        }

        /// <summary> Initializes a new instance of MessagesResult. </summary>
        /// <param name="messages"> Log messages. </param>
        /// <param name="total"> The total number of log messages found. </param>
        internal MessagesResult(IReadOnlyList<MessageOverview> messages, int? total)
        {
            Messages = messages;
            Total = total;
        }

        /// <summary> Log messages. </summary>
        public IReadOnlyList<MessageOverview> Messages { get; }
        /// <summary> The total number of log messages found. </summary>
        public int? Total { get; }
    }
}
