// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Elmah.Io.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class MessagesResult
    {
        /// <summary>
        /// Initializes a new instance of the MessagesResult class.
        /// </summary>
        public MessagesResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessagesResult class.
        /// </summary>
        public MessagesResult(IList<MessageOverview> messages = default(IList<MessageOverview>), int? total = default(int?))
        {
            Messages = messages;
            Total = total;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "messages")]
        public IList<MessageOverview> Messages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

    }
}
