// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Elmah.Io.Client.Models
{
    public partial class Search : IUtf8JsonSerializable
    {
        void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            if (Optional.IsDefined(Query))
            {
                writer.WritePropertyName("query");
                writer.WriteStringValue(Query);
            }
            if (Optional.IsDefined(From))
            {
                writer.WritePropertyName("from");
                writer.WriteStringValue(From.Value, "O");
            }
            if (Optional.IsDefined(To))
            {
                writer.WritePropertyName("to");
                writer.WriteStringValue(To.Value, "O");
            }
            writer.WriteEndObject();
        }
    }
}
