// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Elmah.Io.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Search
    {
        /// <summary>
        /// Initializes a new instance of the Search class.
        /// </summary>
        public Search()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Search class.
        /// </summary>
        /// <param name="query">Lucene query.</param>
        /// <param name="fromProperty">Search from this date.</param>
        /// <param name="to">Search to this date.</param>
        public Search(string query = default(string), System.DateTime? fromProperty = default(System.DateTime?), System.DateTime? to = default(System.DateTime?))
        {
            Query = query;
            FromProperty = fromProperty;
            To = to;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets lucene query.
        /// </summary>
        [JsonProperty(PropertyName = "Query")]
        public string Query { get; set; }

        /// <summary>
        /// Gets or sets search from this date.
        /// </summary>
        [JsonProperty(PropertyName = "From")]
        public System.DateTime? FromProperty { get; set; }

        /// <summary>
        /// Gets or sets search to this date.
        /// </summary>
        [JsonProperty(PropertyName = "To")]
        public System.DateTime? To { get; set; }

    }
}
