// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Elmah.Io.Client.Models
{
    /// <summary> The Search. </summary>
    public partial class Search
    {
        /// <summary> Initializes a new instance of Search. </summary>
        public Search()
        {
        }

        /// <summary> Lucene query. </summary>
        public string Query { get; set; }
        /// <summary> Search from this date. </summary>
        public DateTimeOffset? From { get; set; }
        /// <summary> Search to this date. </summary>
        public DateTimeOffset? To { get; set; }
    }
}
