// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Elmah.Io.Client.Models
{
    /// <summary> The UptimeCheck. </summary>
    public partial class UptimeCheck
    {
        /// <summary> Initializes a new instance of UptimeCheck. </summary>
        internal UptimeCheck()
        {
        }

        /// <summary> Initializes a new instance of UptimeCheck. </summary>
        /// <param name="id"> ID of the uptime check. </param>
        /// <param name="name"> Name of the uptime check. </param>
        /// <param name="url"> Url of the uptime check. </param>
        /// <param name="status"> Current status of the uptime check. </param>
        internal UptimeCheck(string id, string name, string url, string status)
        {
            Id = id;
            Name = name;
            Url = url;
            Status = status;
        }

        /// <summary> ID of the uptime check. </summary>
        public string Id { get; }
        /// <summary> Name of the uptime check. </summary>
        public string Name { get; }
        /// <summary> Url of the uptime check. </summary>
        public string Url { get; }
        /// <summary> Current status of the uptime check. </summary>
        public string Status { get; }
    }
}
