// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Text.Json;
using Azure.Core;

namespace Elmah.Io.Client.Models
{
    public partial class UptimeCheck
    {
        internal static UptimeCheck DeserializeUptimeCheck(JsonElement element)
        {
            Optional<string> id = default;
            Optional<string> name = default;
            Optional<string> url = default;
            Optional<string> status = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"))
                {
                    id = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("name"))
                {
                    name = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("url"))
                {
                    url = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("status"))
                {
                    status = property.Value.GetString();
                    continue;
                }
            }
            return new UptimeCheck(id.Value, name.Value, url.Value, status.Value);
        }
    }
}
