// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Elmah.Io.Client
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Messages.
    /// </summary>
    public static partial class MessagesExtensions
    {
            /// <summary>
            /// Fetch messages from a log.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the messages.
            /// </param>
            /// <param name='pageIndex'>
            /// The page number of the result.
            /// </param>
            /// <param name='pageSize'>
            /// The number of messages to load (max 100) or 15 if not set.
            /// </param>
            /// <param name='query'>
            /// A full-text or Lucene query to limit the messages by.
            /// </param>
            /// <param name='fromParameter'>
            /// A start date and time to search from (not included).
            /// </param>
            /// <param name='to'>
            /// An end date and time to search to (not included).
            /// </param>
            public static ElmahIoApiModelsMessagesResult GetAll(this IMessages operations, string logId, int? pageIndex = default(int?), int? pageSize = default(int?), string query = default(string), DateTime? fromParameter = default(DateTime?), DateTime? to = default(DateTime?))
            {
                return Task.Factory.StartNew(s => ((IMessages)s).GetAllAsync(logId, pageIndex, pageSize, query, fromParameter, to), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Fetch messages from a log.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the messages.
            /// </param>
            /// <param name='pageIndex'>
            /// The page number of the result.
            /// </param>
            /// <param name='pageSize'>
            /// The number of messages to load (max 100) or 15 if not set.
            /// </param>
            /// <param name='query'>
            /// A full-text or Lucene query to limit the messages by.
            /// </param>
            /// <param name='fromParameter'>
            /// A start date and time to search from (not included).
            /// </param>
            /// <param name='to'>
            /// An end date and time to search to (not included).
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ElmahIoApiModelsMessagesResult> GetAllAsync(this IMessages operations, string logId, int? pageIndex = default(int?), int? pageSize = default(int?), string query = default(string), DateTime? fromParameter = default(DateTime?), DateTime? to = default(DateTime?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetAllWithHttpMessagesAsync(logId, pageIndex, pageSize, query, fromParameter, to, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create a new message.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log which should contain the new message.
            /// </param>
            /// <param name='message'>
            /// The message object to create.
            /// </param>
            public static void Create(this IMessages operations, string logId, ElmahIoApiModelsCreateMessage message)
            {
                Task.Factory.StartNew(s => ((IMessages)s).CreateAsync(logId, message), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create a new message.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log which should contain the new message.
            /// </param>
            /// <param name='message'>
            /// The message object to create.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task CreateAsync(this IMessages operations, string logId, ElmahIoApiModelsCreateMessage message, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.CreateWithHttpMessagesAsync(logId, message, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// Deletes a list of messages by logid and query.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the message.
            /// </param>
            /// <param name='search'>
            /// A search object containing query, time filters etc.
            /// </param>
            public static void DeleteAll(this IMessages operations, string logId, ElmahIoApiModelsSearch search)
            {
                Task.Factory.StartNew(s => ((IMessages)s).DeleteAllAsync(logId, search), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Deletes a list of messages by logid and query.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the message.
            /// </param>
            /// <param name='search'>
            /// A search object containing query, time filters etc.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteAllAsync(this IMessages operations, string logId, ElmahIoApiModelsSearch search, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.DeleteAllWithHttpMessagesAsync(logId, search, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// Fetch a message by its ID.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The ID of the message to fetch.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the message.
            /// </param>
            public static ElmahIoApiModelsMessage Get(this IMessages operations, string id, string logId)
            {
                return Task.Factory.StartNew(s => ((IMessages)s).GetAsync(id, logId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Fetch a message by its ID.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The ID of the message to fetch.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the message.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ElmahIoApiModelsMessage> GetAsync(this IMessages operations, string id, string logId, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(id, logId, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Delete a message by its ID.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The ID of the message to delete.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the message.
            /// </param>
            public static void Delete(this IMessages operations, string id, string logId)
            {
                Task.Factory.StartNew(s => ((IMessages)s).DeleteAsync(id, logId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Delete a message by its ID.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The ID of the message to delete.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the message.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task DeleteAsync(this IMessages operations, string id, string logId, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.DeleteWithHttpMessagesAsync(id, logId, null, cancellationToken).ConfigureAwait(false);
            }

            /// <summary>
            /// Hide a message by its ID.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The ID of the message to hide.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the message.
            /// </param>
            public static void Hide(this IMessages operations, string id, string logId)
            {
                Task.Factory.StartNew(s => ((IMessages)s).HideAsync(id, logId), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Hide a message by its ID.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// The ID of the message to hide.
            /// </param>
            /// <param name='logId'>
            /// The ID of the log containing the message.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task HideAsync(this IMessages operations, string id, string logId, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.HideWithHttpMessagesAsync(id, logId, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
