name: build

on:
  push:
    branches: [ main, apiv4 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2025
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      # env:
      #   SECRET_BASE_URL: ${{ secrets.SECRET_BASE_URL }}
      #   SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
      #   SECRET_LOG_ID: ${{ secrets.SECRET_LOG_ID }}
      #   SECRET_HEARTBEAT_ID: ${{ secrets.SECRET_HEARTBEAT_ID }}
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release src/Elmah.Io.Client/Elmah.Io.Client.csproj /p:Version=6.0.${{ github.run_number }}-pre

    - name: Install dotnet-validate
      run: dotnet tool install --global dotnet-validate --version 0.0.1-preview.582

    - name: Validate Elmah.Io.AspNetCore
      run: dotnet-validate package local src/Elmah.Io.Client/bin/Release/Elmah.Io.Client.6.0.${{ github.run_number }}-pre.nupkg

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: nuget-login
      with:
        user: ${{ secrets.NUGET_USER }}
      if: ${{ github.event_name == 'push' }}

    - name: Push
      run: dotnet nuget push src/Elmah.Io.Client/bin/Release/Elmah.Io.Client.6.0.${{ github.run_number }}-pre.nupkg --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}

    - name: Create Tag
      uses: negz/create-tag@v1
      with:
        version: 6.0.${{ github.run_number }}-pre
        token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event_name == 'push' }}

    - name: Refresh Bugster
      uses: elmahio/actions/refresh-bugster-repository@v1.2
      with:
        signing: ${{ secrets.BUGSTER_SIGNING_KEY }}
        url: ${{ secrets.FUNCTION_APP_URL }}
        repository: ${{ github.event.repository.name }}
      if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}